---
version: 2
registries:
  ruby-github:
    type: rubygems-server
    url: https://rubygems.pkg.github.com/appfolio
    token: "${{secrets.READ_ONLY_PACKAGES_CCIMU}}"
updates:
- package-ecosystem: bundler
  directory: "/sunspot"
  schedule:
    interval: daily
  pull-request-branch-name:
    separator: "-"
  registries: "*"
- package-ecosystem: bundler
  directory: "/sunspot_solr"
  schedule:
    interval: daily
  pull-request-branch-name:
    separator: "-"
  registries: "*"
