rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.2.3
  # - rbx-2.0
  # - jruby

env:
  - GEM=sunspot
  - GEM=sunspot_rails RAILS=2.3.14
  - GEM=sunspot_rails RAILS=3.0.15
  - GEM=sunspot_rails RAILS=3.1.6
  - GEM=sunspot_rails RAILS=3.2.6
  - GEM=sunspot_rails RAILS=4.1.12
  - GEM=sunspot_rails RAILS=4.2.4

# Limit the size of the matrix by only performing one build against
# 1.8.7 and 1.9.2
matrix:
  exclude:
    - rvm: 1.8.7
      env: GEM=sunspot_rails RAILS=3.0.15
    - rvm: 1.8.7
      env: GEM=sunspot_rails RAILS=3.1.6
    - rvm: 1.8.7
      env: GEM=sunspot_rails RAILS=3.2.6
    - rvm: 1.9.2
      env: GEM=sunspot_rails RAILS=3.0.15
    - rvm: 1.9.2
      env: GEM=sunspot_rails RAILS=3.1.6
    - rvm: 1.9.2
      env: GEM=sunspot_rails RAILS=3.2.6
    - rvm: 1.9.3
      env: GEM=sunspot_rails RAILS=2.3.14
    - rvm: 2.2.3
      env: GEM=sunspot_rails RAILS=4.1.12
    - rvm: 2.2.3
      env: GEM=sunspot_rails RAILS=4.2.4

script:
  - ci/travis.sh
